apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ikramboussouifa-sys/devops-enterprise-project
    targetRevision: develop
    path: k8s/helm/devops-api
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true