services:

  postgres:
    image: postgres:17
    container_name: devops-postgres

    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DevOps123!

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: devops-api

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:DevOps123!@postgres:5432/devopsdb

    ports:
      - "8000:8000"

volumes:
  postgres_data: