apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: devops
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: env-file
              mountPath: /app/.env.example
              subPath: .env.example
      volumes:
        - name: env-file
          configMap:
            name: {{ .Release.Name }}-env